info:
  name: Create Role
  type: http
  seq: 1

http:
  method: POST
  url: "{{base_url}}/api/v1/roles"
  body:
    type: json
    data: |-
      {
        "name": "Professor",
        "description": "Permite gerenciar aulas"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5